### ISSUE TITLE
How to understand $clientUserId

### ISSUE THREAD

**Issue by logiwr** [docusign/qs-php#1]
In qs-01 we use $clientUserId = '123' to enable embedded signing.

The code works for me with this variable and I get an API error if I don't set it. So far so good, but is it ok to just leave this as '123'? In the comment it says 'Represents the signer's userId within your application.' Where can I find the signer's userId? And what if the signer is not a member of my application?

Sorry I'm totally new to DocuSign

**Comment by LarryKlugerDS** [comment]
Hi,
(General questions about the API are best answered via StackOverflow with the docusignapi tag)

**Re: setting the clientUserId** -- the idea is that the value of the clientUserId should reflect the user id of the user within **your** application. Remember that with embedded signing, your application has a primary responsibility for authenticating who the signer is. 

For example, if the signer logs into your application, then their user id within your application should be used. This is the most common case.

If the signer doesn't log into your application, then how do you know that the signer is who they say they are?  One way is to request additional authentication steps by DocuSign as part of the signing process. 

If you don't have any login id for the signer, you can make up a value by using the signer's email.

Re: **Signer is not a member of my application** In this case, you'd need to make up a clientUserId for them (and also figure out how you (or DocuSign) will authenticate their identity.

**Comment by logiwr** [comment]
Alright I think I got it. It's just about how I keep track of recipients inside my own code.
I thought "inside your application" means I have to create the user somehow in my DocuSign account in the "My apps / Integrator keys" section, so that's why I was confused.

Thanks for your help!
