### ISSUE TITLE
Quick Start API calls are out-of-date

### ISSUE THREAD

**Issue by FlavorPurveyor** [docusign/qs-php#5]
See error below:
Fatal error: Uncaught Error: Class 'DocuSign\eSign\ApiClient' not found in qs-01-php-embed-signing-ceremony.php:90 Stack trace: #0 qs-01-php-embed-signing-ceremony.php(118): embedded_signing_ceremony() #1 {main} thrown in qs-01-php-embed-signing-ceremony.php on line 90

The Class 'DocuSign\eSign\ApiClient' has been moved to a different namespace 'DocuSign\eSign\Client\ApiClient'. By changing this single line of code the Quick Start will function as needed.

**Comment by LarryKlugerDS** [comment]
Thank you for the report. I have filed internal ticket DEVDOCS-1653 for our examples team to investigate and fix.

**Comment by LarryKlugerDS** [comment]
Our engineering group has reported that this bug has been fixed. Please comment/re-open this issue if it is still a problem for you. 

Thanks,
Larry
